### ISSUE TITLE
Bug on expiration date

### ISSUE THREAD

**Issue by gimp23** [charmtraders-apps/issue_tracker#1]
I select a new date to start a backtest
Then I open the window to select the expiration date
The expiration dates available are shown only for 20160104 Mo
As a result it's impossible to use the software

I use Chrome on a 2013 Macbook Pro with MacOS BigSur

<img width="1440" alt="Schermata 2024-02-01 alle 18 48 45" src="https://github.com/charmtraders-apps/issue_tracker/assets/158504723/63bb6566-4e8f-4fb5-847d-96166aca3842">

**Comment by charmtraders-apps** [comment]
Thanks for reporting. Issue is fixed.

**Comment by charmtraders-apps** [comment]
Issue is fixed.

**Comment by gimp23** [comment]
Thank you!
