### ISSUE TITLE
Missing Database Selection Option in OptiTrade Tool

### ISSUE THREAD

**Issue by hash123shaikh** [charmtraders-apps/issue_tracker#10]
**Summary:**

I have encountered a significant issue within the OptiTrade tool where the option to select a database for operations like analyzing or trading is not visible. This problem prevents me from accessing different databases such as SPX, which is essential for my trading activities.

**Steps to Reproduce:**

1. Open the OptiTrade tool and log in with the necessary credentials.
2. Navigate to the section of the tool where database selection is typically done (e.g., under a specific tab or dropdown menu).
3. Attempt to select a database for executing operations.

**Expected Behavior:**

The tool should display a list of available databases (e.g., SPX, AEX) in a dropdown menu or similar interface element, allowing me to select the desired database for my trading or analysis activities.

**Actual Behavior:**

The option to select any database does not appear on the interface. There are no dropdown menus, lists, or any other interface elements that allow for the selection of a database like SPX.

**Frequency:**

This issue occurs rarely when I attempt to access the database selection functionality, indicating a rarely occurring problem with the tool's user interface.

**Impact:**

This bug significantly hampers my ability to effectively use the OptiTrade tool, as I cannot access different databases for necessary operations. The lack of database selection capability restricts my trading strategy implementation and market analysis efficiency.

![missing option database](https://github.com/charmtraders-apps/issue_tracker/assets/80396371/62df9b29-e330-4ec3-8405-32af1b9c7402)

**Comment by charmtraders-apps** [comment]
![Screenshot 2024-04-22 at 12 44 47](https://github.com/charmtraders-apps/issue_tracker/assets/151726541/fbb9bd4e-a898-443d-9b10-f504ddc2a7a2)

We cannot replicate the issue, databases are accessible.

**Comment by hash123shaikh** [comment]
Thank you for your continued support as we try to resolve the database selection issue in the OptiTrade tool.

I have observed some inconsistent behaviour that may provide further insight into the problem:

- **Different System Behavior:** When I log in to the OptiTrade tool on a different system, the database selection option appears as expected, suggesting that the feature works correctly under certain conditions.

- **Current System Issue:** However, when using my usual system, the same database selection option does not appear. This discrepancy occurs even though I have not logged out between sessions, which might indicate a potential issue with how session data is handled or displayed in different environments.

- **Intermittent Issue:** It's important to note that this problem does not always occur with consistent reproducibility, which suggests that it might be triggered by specific conditions or configurations unique to my primary system.

To assist in further diagnosing this issue, could we explore the following:

- **System Configuration and Logs:** Are there specific logs from my system that would be useful for your team to review? If so, could you guide me on how to retrieve and send these to you?

- **Detailed Diagnostic Steps:** Any additional diagnostic steps you can provide would be greatly appreciated. This might include checking certain settings, and configurations, or performing specific actions that could help pinpoint the source of the inconsistency.

- **Session Data Handling:** Could there be an issue with how session data is managed on different systems or browsers? Any insights or checks related to this would be helpful.

I am committed to resolving this so that I can utilize the OptiTrade tool effectively across all my devices. I look forward to your guidance and am ready to provide any additional information required.

Thank you once again for your diligence and cooperation.
