### ISSUE TITLE
Request a Monitoring View

### ISSUE THREAD

**Issue by rkinman** [charmtraders-apps/issue_tracker#11]
Having a monitoring view would be beneficial, where one could observe the risk graphs for each open trade they wish to monitor in a grid view. For a manual trader juggling multiple complex positions, it's advantageous to have a visual representation of all trade structures at once, rather than having to individually access each trade log reference.

**Comment by charmtraders-apps** [comment]
Added in release, V24.05.03 beta, which will be rolled out in the weekend of May 18/19 2024.
