### ISSUE TITLE
Daily Timeframe Navigation for Chart Analysis in OptiTrade Tool

### ISSUE THREAD

**Issue by hash123shaikh** [charmtraders-apps/issue_tracker#2]
**Is your feature request related to a problem? Please describe.**
The current OptiTrade tool's chart animation is limited to an hourly timeframe, which is ideal for short-term trade analysis. However, for longer-term strategies, it's often more insightful to view chart changes on a daily basis. The inability to view chart changes on a daily basis can hinder comprehensive analysis over extended periods.

**Describe the solution you'd like**
I would like the tool to offer an option that allows users to navigate and animate the charts on a daily basis. A user-friendly option, such as a dropdown menu or a switch within the interface, should enable the toggle between hourly and daily views, offering enhanced flexibility for risk analysis across various time frames.

**Describe alternatives you've considered**
An alternative could be a toggle feature that allows users to switch between hourly and daily chart animations. This way, users can choose the most relevant time frame for their trading strategy without being restricted to one type of data granularity.

**Additional context**
This feature would be particularly useful for end-of-day analysis and for traders who focus on daily price movements rather than intra-day fluctuations.
![Screenshot (310)](https://github.com/charmtraders-apps/issue_tracker/assets/80396371/b90e30de-3439-40c4-ba91-a57f8d50b5ee)

**Comment by charmtraders-apps** [comment]
Thank you for your feedback! 

Now, users can select between two distinct databases for their analysis needs: the _backtrack database, which offers hourly data for detailed insights, and the _backtrack_EOD database, designed with End-Of-Day (EOD) data for a simplified, daily overview. This choice allows for greater flexibility in analysis, enabling users to switch effortlessly between detailed hourly views and concise daily summaries without the need for a toggle. This streamlined approach is aimed at improving usability and catering to diverse risk analysis requirements more effectively.

**Comment by hash123shaikh** [comment]
Thank you very much for the prompt and thoughtful reply to my feature request. I appreciate the team's efforts to enhance the tool's flexibility by introducing the _backtrack and _backtrack_EOD databases for hourly and end-of-day data analysis, respectively. This dual-database approach indeed offers a more streamlined solution for switching between detailed and summary views, catering to a wide range of analysis needs.

Additionally, are there any considerations or best practices to keep in mind when switching between these databases to ensure data consistency and accuracy in analysis?

Thank you again for your dedication to improving the OptiTrade tool and for keeping users at the forefront of these developments.
