### ISSUE TITLE
Multi-Selection of Trade Logs for Aggregated Risk Graph Analysis

### ISSUE THREAD

**Issue by hash123shaikh** [charmtraders-apps/issue_tracker#3]
**Is your feature request related to a problem? Please describe.**
Currently, the OptiTrade tool restricts users to selecting only one trade log at a time for review in the trade log section. For traders managing multiple trades, this limitation prevents a consolidated view of the aggregate risk across various trade logs. This can be inefficient for those needing to assess the combined risk profile of all their trades simultaneously.

**Describe the solution you'd like**
I suggest the tool be enhanced to allow the selection of multiple trade logs simultaneously. This could be achieved by replacing the current bullet point selection with checkboxes next to each trade log entry. Users could then select multiple checkboxes to view the cumulative risk graph of the selected trades on a single coordinate plane.

**Additional context**
Having the ability to select multiple trade logs for simultaneous risk graph analysis would be invaluable for traders who operate with diversified strategies or multiple concurrent trades. It would provide a holistic view of their risk exposure and help with more informed decision-making.
![Screenshot (10)](https://github.com/charmtraders-apps/issue_tracker/assets/80396371/dc82550c-c2bb-4245-9c8c-cf794501d1da)

**Comment by charmtraders-apps** [comment]
Thank you for reaching out with your feature request and for providing detailed insight into how you envision enhancing the OptiTrade tool. We understand the importance of assessing cumulative risk across multiple trades and the efficiency benefits of viewing these in a consolidated manner.

Our tool is designed with the philosophy of maintaining a unified trade log that captures all trading activities. This approach encourages users to consolidate all trades within a single log, utilizing trade references to distinguish between different trades. By employing trade references, you can effectively manage and analyze multiple trades as discrete entities within the same log. Additionally, the "event" feature is available for adding comments or notes to each trade, allowing for further clarification and organization.

We believe this methodology streamlines the process of risk assessment and decision-making by providing a cohesive overview of all trading activities. It simplifies the management of diversified strategies or multiple concurrent trades under a unified framework, enabling a comprehensive view of your risk exposure without the need to toggle between separate trade logs.

We appreciate your suggestion and understand it comes from a need to optimize trading strategy analysis. While our current design focuses on single-log management for efficiency and simplicity, we continually evaluate user feedback for potential enhancements. Your input is invaluable to us, and we encourage you to explore using trade references and events to achieve a similar outcome to what you described.
