### ISSUE TITLE
Custom Selection of t-date (theoretical date) for Static Risk Graph Analysis

### ISSUE THREAD

**Issue by hash123shaikh** [charmtraders-apps/issue_tracker#4]
**Is your feature request related to a problem? Please describe.**
The risk graph functionality within the OptiTrade tool currently presents a limitation by only displaying profits for four predetermined theoretical dates (t-dates) associated with theoretical prices (t-prices). The inability to select or view additional t-dates restricts traders from conducting a thorough analysis of their strategy's profit potential across a broader range of future time points.

**Describe the solution you'd like**
To address this limitation, I propose an enhancement to the risk graph feature that would allow users to select additional theoretical dates beyond the four predetermined ones. This could be facilitated through an interactive component such as a sidebar or dropdown menu within the risk graph interface. Enabling this functionality would allow traders to analyze the profit potential of their strategies on any chosen theoretical date, providing a more comprehensive understanding of strategy performance over time.
![Screenshot (12)](https://github.com/charmtraders-apps/issue_tracker/assets/80396371/757eee79-5434-4a02-9e30-a5c4c54f1d06)

**Comment by charmtraders-apps** [comment]
We understand your request for adding flexibility in selecting theoretical dates (t-dates) beyond the four predetermined ones currently available. This feature, as you've rightly pointed out, could potentially offer a more granular analysis of a strategy's performance over its lifespan.

Upon thorough evaluation, including an assessment of the underlying methodologies and user interface considerations, we have decided to maintain the present configuration, which displays profits for four specific theoretical dates. These dates are strategically chosen to fall within the critical range between the strategy's start date and its expiration date. This selection is guided by the principle of providing a meaningful snapshot of the strategy's performance at pivotal moments, ensuring relevance and actionable insights.

It's important to note that the Black-Scholes model, which underpins much of the theoretical pricing and date analysis, operates within the realm of approximation. While it offers valuable insights, it is predicated on assumptions that mean exact dates may not yield the precision expected. This approximation nature reinforces our approach to limit the selection to a curated set of dates, ensuring that the analysis remains both practical and grounded in the model's inherent accuracy range.

Expanding the number of selectable dates, while theoretically enriching, could inadvertently introduce complexity that might obscure the tool's usability and the immediate clarity of insights derived from it. Our commitment is to strike a balance—offering robust analytical capabilities while preserving simplicity, accuracy, and the tool's overall navigability for traders at all expertise levels.

We assure you that this decision was made after careful consideration of both the technical and user experience implications. We remain dedicated to continuous enhancement of the OptiTrade tool, guided by insightful user feedback like yours and the evolving needs of the trading community.
