### ISSUE TITLE
Uninformative Error Messaging During Trade Log Import in OptiTrade Tool

### ISSUE THREAD

**Issue by hash123shaikh** [charmtraders-apps/issue_tracker#7]
**Summary:**
When importing an Excel file into the OptiTrade tool's trade log, if the column names in the file do not match the expected column names, the tool fails to display the imported data correctly in the risk graph. Instead of providing a clear error message about the mismatched column names, the tool only displays a vague message, leading to confusion about the cause of the issue.

**Steps to Reproduce:**
1.	Navigate to the trade log import section of the OptiTrade tool.
2.	Attempt to import an Excel file for trade analysis, ensuring that at least one column name does not match the tool's expected column format.
3.	After the import, access the risk graph to view the results of the imported trade data.

**Expected Behavior:**
The tool should validate the column names upon import and immediately flag any discrepancies with clear, explicit error messages. This would inform the user of the specific column names that need correction, preventing unsuccessful imports and saving time.

**Actual Behavior:**
The tool completes the import process without any indication of column name issues. When attempting to view the imported data on the risk graph, the tool displays "Symbols in trade log: ['-']" without explaining the underlying problem, leaving users without a clear path to resolve the issue.

**Frequency:**
The issue occurs every time there is a discrepancy in column names between the imported Excel file and the tool's expected format.

**Environment:**
•	OS: Windows 10 Pro, Version 22H2
•	CPU: Intel(R) Core(TM) i5-6500 @ 3.20GHz
•	RAM: 8.00 GB
•	System Architecture: 64-bit OS, x64-based processor

**Suggested Fix:**
Implement a validation check during the import process that specifically verifies if the Excel file's column names match the expected names. If a mismatch is detected, the tool should display a clear and actionable error message, specifying which column names are incorrect.
![Screenshot (14)](https://github.com/charmtraders-apps/issue_tracker/assets/80396371/7a0e1574-f16b-45ab-b037-7acd21eec927)

**Comment by charmtraders-apps** [comment]
Thank you for your detailed feedback and for bringing this issue to our attention. We understand how crucial clear and informative feedback is within the OptiTrade tool, especially when it comes to streamlining the import process and ensuring data integrity in the trade log.

Based on your valuable input, we are pleased to inform you that we have prioritized the enhancement of our import validation process. In our upcoming release, we will implement a new feature that checks the column names of Excel files upon import. This validation will ensure that the column names match the tool's expected format.

**Comment by hash123shaikh** [comment]
I'm truly grateful for the prompt attention given to the feedback concerning the trade log import process. It's reassuring to know that the team not only acknowledges the significance of clear and informative feedback during the import process but also takes proactive steps to enhance user experience and data integrity.

Ensuring that imported data aligns with the expected format not only streamlines the import process but also enhances the overall user experience by preventing potential errors and confusion.

Thank you once again for your commitment to excellence and for keeping the user community informed and engaged. I look forward to continuing to contribute to the OptiTrade tool's evolution and success.

**Comment by charmtraders-apps** [comment]
Implemented in release: V24.02.02 beta
