### ISSUE TITLE
Date Format Clarity and Labelling of SPX Price in OptiTrade Tool

### ISSUE THREAD

**Issue by hash123shaikh** [charmtraders-apps/issue_tracker#8]
**Summary:**
Users have encountered two separate but related usability issues within the OptiTrade tool: (1) the presentation of dates in the format YYYYMMDD, which can be challenging to interpret quickly, and (2) an unlabelled value displayed above the VIX, known to represent the underlying price of SPX but not explicitly identified as such.

**Issue 1: Date Format Usability**
**Steps to Reproduce:**
1.	Observe the format in which dates are presented.

**Expected Behaviour:**
Dates should be displayed in a user-friendly format that separates year, month, and day with slashes or dashes (e.g., YYYY/MM/DD or YYYY-MM-DD) for easier readability and comprehension.

**Actual Behaviour:**
Dates are currently displayed in a concatenated format without separators (YYYYMMDD), which may lead to confusion and difficulty in quickly understanding the date.

**Issue 2: Unlabelled SPX Price above VIX**
**Steps to Reproduce:**
1.	View the VIX value display area within the tool.
2.	Note the numerical value presented above the VIX without explicit labelling.

**Expected Behaviour:**
All values displayed in the tool, especially those critical to trading decisions like the SPX price, should be clearly labelled to avoid confusion and ensure users understand what each value represents.

**Actual Behaviour:**
The underlying SPX price is displayed above the VIX without a clear label, leading to potential misunderstanding among users unfamiliar with the convention that this value represents the SPX price.

**Frequency:**
Both issues are persistent across all instances of the tool where the respective elements are present.

**Environment:**
•	OS: Windows 10 Pro, Version 22H2
•	CPU: Intel(R) Core(TM) i5-6500 @ 3.20GHz
•	RAM: 8.00 GB
•	System Architecture: 64-bit OS, x64-based processor

**Suggested Fix:**
1.	**For Issue 1:** Adopt a more intuitive date format by including separators between the year, month, and day components. Providing options for users to select their preferred date format could further enhance usability.
2.	**For Issue 2:** Introduce a clear label (e.g., "SPX Price:") for the value displayed above the VIX to ensure users can easily understand what the value represents.
![Screenshot (15)](https://github.com/charmtraders-apps/issue_tracker/assets/80396371/d5905bed-a28f-4338-b005-5451bc8cefa6)

**Comment by charmtraders-apps** [comment]
Thank you very much for your valuable feedback regarding the usability of the OptiTrade tool. We genuinely appreciate the time you took to share your observations and understand how these aspects impact your experience with our application.

SPX Price Labeling: We're pleased to inform you that we have addressed the feedback regarding the unlabelled value displayed above the VIX. We recognize the importance of clear and intuitive labeling for all data presented within OptiTrade. To improve clarity, we have implemented labeling for the SPX price, which will be clearly identified in the application's next release. We hope this enhancement will make your interactions with OptiTrade more efficient and enjoyable.

Date Format Consistency: Regarding the presentation of dates in the format YYYYMMDD, we've conducted a thorough review of our design choices. Our aim has always been to ensure consistency and accuracy in data presentation across the entire application. After careful consideration, we've decided to maintain the current date format (YYYYMMDD) throughout OptiTrade. We understand that preferences for date formats can vary, and we apologize for any inconvenience this may cause. However, this decision was made to preserve data uniformity and prevent potential confusion that could arise from using multiple date formats. We appreciate your understanding and assure you that this choice was made with the best interests of all our users in mind.

We're committed to continually improving OptiTrade and genuinely value your feedback as it helps us make better decisions that enhance user experience. Please keep sharing your insights and suggestions with us.

**Comment by hash123shaikh** [comment]
Thank you for your thoughtful and detailed response to my feedback. I genuinely appreciate the OptiTrade team's efforts to address the concerns raised, especially the upcoming implementation of SPX price labelling. This update is sure to enhance the tool's clarity and overall usability, and I look forward to seeing it in action.

Regarding the date format (YYYYMMDD), I understand the rationale behind maintaining consistency across the application to avoid confusion and ensure data uniformity.

However, I find that the current format can sometimes be challenging to interpret quickly, particularly when analysing data over extended periods. To enhance readability without compromising the consistency you aim for, might I suggest adopting the YYYY-MM-DD format across the tool? This format is ISO 8601 compliant, widely recognized, and retains the logical order of year, month, and day, while the hyphens improve visual separation and readability.

Introducing the YYYY-MM-DD date format could offer a subtle yet effective improvement to user experience, making dates instantly more recognizable and easier to understand at a glance. Such a change could further refine the tool's interface, aligning with the best practices in data presentation while still adhering to the principle of uniformity across the application.

I hope this suggestion is taken as a constructive contribution aimed at enhancing the OptiTrade experience for all users. Thank you once again for considering my feedback, and I am eager to continue contributing to the improvement of the OptiTrade tool.
